spring:
  application:
    name: localup
  profiles:
    active: local

tour-api:
  base-url: https://apis.data.go.kr
  mobile-os: WEB
  mobile-app: LocalUp
  # 한국관광공사_관광지별 연관 관광지 정보
  # link: https://www.data.go.kr/data/15128560/openapi.do
  tar-rlte-tar-service:
    first-path: /B551011/TarRlteTarService1
    # 지역기반 관광지별 연관 관광지 정보 목록 조회
    area-based-list:
      second-path: /areaBasedList1
      response-type: JSON

  # 한국관광공사_기초지자체 중심 관광지 정보
  # link: https://www.data.go.kr/data/15128559/openapi.do
  locgo-hub-tar-service:
    first-path: /B551011/LocgoHubTarService1
    # 지역기반 중심 관광지 정보 목록 조회
    area-based-list:
      second-path: /areaBasedList1
      response-type: JSON

  # 한국관광공사_관광지 집중률 방문자 추이 예측 정보
  # link: https://www.data.go.kr/data/15128555/openapi.do
  tats-cnctr-rate-service:
    first-path: /B551011/TatsCnctrRateService
    # 관광지 집중률 정보 목록조회
    tats-cnctr-rated-list:
      second-path: /tatsCnctrRatedList

  # 한국관광공사_관광빅데이터 정보서비스_GW
  # link: https://www.data.go.kr/data/15101972/openapi.do
  data-lab-service:
    first-path: /B551011/DataLabService
    # 광역 지자체 지역방문자수 집계 데이터 정보 조회
    metco-regn-visitr-dd-list:
      second-path: /metcoRegnVisitrDDList
    # 기초 지자체 지역방문자수 집계 데이터 정보 조회
    locgo-regn-visitr-dd-list:
      second-path: /locgoRegnVisitrDDList

etc-api:
  # 기상청 (Korea Meteorological Administration)
  kma:
    base-url: https://apis.data.go.kr
    # 기상청_단기예보 ((구)_동네예보) 조회서비스
    # link: https://www.data.go.kr/data/15084084/openapi.do
    vilage-fcst-info-service:
      first-path: /1360000/VilageFcstInfoService_2.0
      # 초단기실황조회
      get-ultra-srt-ncst:
        second-path: /getUltraSrtNcst
        date-type: JSON
      # 예보버전조회
      get-fcst-version:
        second-path: /getFcstVersion
        date-type: JSON
