spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/localup?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: root
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

token:
  access-token:
    name: accessToken
    expiration-seconds: 86400

tour-api:
  # 한국관광공사_관광지별 연관 관광지 정보
  # link: https://www.data.go.kr/data/15128560/openapi.do
  tar-rlte-tar-service:
    service-key: ${TAR_RLTE_TAR_SERVICE_KEY}

  # 한국관광공사_관광지 집중률 방문자 추이 예측 정보
  tats-cnctr-rate-service:
    service-key: ${TATS_CNCTR_RATE_SERVICE_KEY}
  data-lab-service:
    service-key: ${DATA_LAB_SERVICE}

etc-api:
  # 기상청 (Korea Meteorological Administration)
  kma:
    vilage-fcst-info-service:
      service-key: ${VILAGE_FCST_INFO_SERVICE_KEY}
