spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

token:
  access-token:
    name: accessToken
    expiration-seconds: 86400

tour-api:
  # 한국관광공사_관광지 집중률 방문자 추이 예측 정보
  tats-cnctr-rate-service:
    service-key: ${TATS_CNCTR_RATE_SERVICE_KEY}
