services:
  app:
    image: localup-backend:latest
    container_name: localup-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: unless-stopped
